### ISSUE TITLE
What kind of hardware is used in training？

### ISSUE THREAD

**Issue by cccrystalyang** [twhui/RM-Depth#5]
Dear Tak-Wai Hui,  

Thanks for sharing this work.  I am a student and interested in this job.

How many GPUs are used in this paper during training? What type of GPU is used and  what is the size of GPU memory?

Looking forward for your reply.

**Comment by twhui** [comment]
I used 4 to 8 Titan X GPUs.

**Comment by cccrystalyang** [comment]
Thanks for your timely reply and look forward to your next work.
