### ISSUE TITLE
Depth prediction in npy format

### ISSUE THREAD

**Issue by HoangChuongNguyen** [twhui/RM-Depth#7]
Hi, thank you for the great work !!!
I saw that the depth predictions are made public, however, they are stored in jpeg format which makes it difficult to evaluate the predicted depth. 
Could you please upload the predicted depth as the original value produced by the model? Or could you show us how to convert from provided depth image back to the originally predicted depth value?

**Comment by twhui** [comment]
I don't use npy format. For visual comparision, I think jpeg format is enough.
